# Site settings
title: Katyanna Moura
email: amelie.kn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Amelia's personal & technical blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katyanna.github.io" # the base hostname & protocol for your site
twitter_username: amelie_kn
github_username:  katyanna
permalink: /blog/:title

# Build settings
markdown: kramdown
